#!/bin/bash -e

cd frontend
{
  echo "REACT_APP_AWS_KEY=$AWS_ACCESS_KEY_ID";
  echo "REACT_APP_AWS_SECRET=$AWS_SECRET_ACCESS_KEY";
  echo "REACT_APP_OPTIMAL_LINEUP_LAMBDA=$REACT_APP_OPTIMAL_LINEUP_LAMBDA";
  echo "REACT_APP_FANDUEL_LAMBDA=$REACT_APP_FANDUEL_LAMBDA";
  echo "REACT_APP_DRAFTKINGS_LAMBDA=$REACT_APP_DRAFTKINGS_LAMBDA";
  echo "REACT_APP_PROJECTIONS_LAMBDA=$REACT_APP_PROJECTIONS_LAMBDA";
  echo "REACT_APP_OPPONENT_RANKS_LAMBDA=$REACT_APP_OPPONENT_RANKS_LAMBDA";
  echo "REACT_APP_INJURIES_LAMBDA=$REACT_APP_INJURIES_LAMBDA";
  echo "REACT_APP_GOALIE_SCRAPER_LAMBDA=$REACT_APP_GOALIE_SCRAPER_LAMBDA";
} >> .env

cat .env
