export const teamAbbreviations = {
    'Ari': 'Arizona Cardinals',
    'Atl': 'Atlanta Falcons',
    'Bal': 'Baltimore Ravens',
    'Buf': 'Buffalo Bills',
    'Car': 'Carolina Panthers',
    'Chi': 'Chicago Bears',
    'Cin': 'Cincinnati Bengals',
    'Cle': 'Cleveland Browns',
    'Dal': 'Dallas Cowboys',
    'Den': 'Denver Broncos',
    'Det': 'Detroit Lions',
    'GB': 'Green Bay Packers',
    'Hou': 'Houston Texans',
    'Ind': 'Indianapolis Colts',
    'Jax': 'Jacksonville Jaguars',
    'KC': 'Kansas City Chiefs',
    'LAC': 'Los Angeles Chargers',
    'LAR': 'Los Angeles Rams',
    'Mia': 'Miami Dolphins',
    'Min': 'Minnesota Vikings',
    'NE': 'New England Patriots',
    'NO': 'New Orleans Saints',
    'NYG': 'New York Giants',
    'NYJ': 'New York Jets',
    'Oak': 'Oakland Raiders', 
    'Phi': 'Philadelphia Eagles',
    'Pit': 'Pittsburgh Steelers',
    'SF': 'San Francisco 49ers',
    'Sea': 'Seattle Seahawks',
    'TB': 'Tampa Bay Buccaneers',
    'Ten': 'Tennessee Titans',
    'Was': 'Washington'
};